### ISSUE TITLE
Impossible to set false as value

### ISSUE THREAD

**Issue by palant** [OLIOEX/gulp-json-modify#1]
The following code will currently error out:

```
jsonModify({
  key: "browser_action.browser_style",
  value: false
});
```

Reason: `Missing "value" option`. Same happens if you specify zero or an empty string as value. The issue is caused by [this line](https://github.com/OLIOEX/gulp-json-modify/blob/c4b55fa/index.js#L29), it should really be `if (typeof opts.value == "undefined")`.

**Comment by lloydwatkin** [comment]
Thanks for the spot, just made pr #2, we'll get it merged and deployed ASAP.

**Comment by lloydwatkin** [comment]
Deployed as `v1.0.1`
