### ISSUE TITLE
tasks.jsonModify is not a function

### ISSUE THREAD

**Issue by NexxusPlexx** [OLIOEX/gulp-json-modify#3]
When I run my gulp command I get this error: **tasks.jsonModify is not a function**, could you please help me ? I'm stuck

**Comment by lloydwatkin** [comment]
Have you required the module in your script, e.g.:

```javascript
const jsonModify = require('gulp-json-modify')

**Comment by NexxusPlexx** [comment]
Yes, here is what my code looks like:

``` js
import gulp from 'gulp';
import tasks from 'gulp-json-modify';

gulp.task('deploy:set-app-version', function () {
    gulp.src([ '../parameters.json' ])
        .pipe(tasks.jsonModify({
            key: 'version',
            value: '1'
        }))
        .pipe(gulp.dest('../'));
});

``` 

I also try require notation:

``` js

import gulp from 'gulp';
var tasks = require('gulp-json-modify');

gulp.task('deploy:set-app-version', function () {
    gulp.src([ '../parameters.json' ])
        .pipe(tasks.jsonModify({
            key: 'version',
            value: '1'
        }))
        .pipe(gulp.dest('../'));
})

```

Error:

![screen shot 2017-04-06 at 12 00 50 pm](https://cloud.githubusercontent.com/assets/4671429/24766395/bbc52d24-1ac0-11e7-9d70-521ee5381ef8.png)

**Comment by lloydwatkin** [comment]
The problem here is that "tasks" is what you should be using and not a non-existent key of the object.

**Comment by NexxusPlexx** [comment]
Yes you right my bad thanks, but now is not updating the file although in the console the ouput is Updated **key** to **value** , you have an idea why is not modifying the file ?

![screen shot 2017-04-06 at 1 04 07 pm](https://cloud.githubusercontent.com/assets/4671429/24768793/9fa5da9a-1ac9-11e7-9d53-de89990ac4b1.png)

**Comment by lloydwatkin** [comment]
Is your file being written to the parent directory?
