### ISSUE TITLE
Adding instead of Modifying

### ISSUE THREAD

**Issue by nickolaschong** [OLIOEX/gulp-json-modify#4]
JSON File
``` 
{
    "app.version": "v3.2.71",
}
```

Code Snippet
```
.pipe(jsonModify({ key: "app.version", value: "2.0.0" }))
```

Result
```
{
   "app.version": "v3.2.71",
   "app": {
        "version": "2.0.0"
    }
}
```

**Comment by lloydwatkin** [comment]
Hi, this is to be expected since dot notation is used to denote subkeys. So this would be ugly but I'd suggest replacing `app.version` with `app-version` and the swapping back after the modification?

**Comment by nickolaschong** [comment]
Thanks, will take into consideration =)
